#ifndef DEFINITIONS_H
#define DEFINITIONS_H

#define DEFAULT_WINDOW_SIZE 1024
#define DEFAULT_WORLD_SIZE 20.f
#define DEFAULT_HOP_SIZE 512
#define WORLD_SIZE_SCALE 2
#define WORLD_VOXEL_SCALE 10

#endif
